services:
  graphiti-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      - NEO4J_URI=neo4j+s://a041dd4c.databases.neo4j.io  # Use your Aura URI
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=your_secure_password              # Replace with your actual password
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - PATH=/root/.local/bin:${PATH}
    ports:
      - "8000:8000"
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]

